### PR TITLE
Bugfix for loading correct resolver files in production build

### LINKED ISSUE #100: Can't start node server in production
## Current behavior
When running `yarn build` and then `yarn start` the server fails to start because of this error:

```
/home/user/storefront-api/packages/default-catalog/graphql/elasticsearch/root.resolver.ts:15
export default resolver;
^^^^^^

SyntaxError: Unexpected token 'export'
...
```

## Expected behavior

The server should start normally.

## Steps to reproduce the issue

1. Clone fresh version of the repo
2. Run `yarn`
3. Run `yarn build`
4. Run `yarn start`

## Repository

https://github.com/DivanteLtd/storefront-api

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: N/A
- OS: Mac OS Catalina 10.15.7
- Node: 14.14.0
- Code Version: `master` and `develop`

## Additional information

For some reason node is trying to load the .ts files instead of the compiled .js files.

### PR DESCRIPTION
**Pull request by cewald**
### Related issues

closes #100

### Short description and why it's useful

Prevents exception during start in production mode.

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/storefront-api/blob/develop/CONTRIBUTING.md)

### CODE REVIEW

File: packages/lib/helpers/graphql.ts [hunk 1]
```diff
@@ -1,18 +1,19 @@
 import path from 'path';
 import { fileLoader } from 'merge-graphql-schemas';
 
-export function loadModuleResolversArray (graphQlPath: string, extensionsPath?: string) {
-  const rootResolvers = fileLoader(path.join(graphQlPath, '*.resolver.{js,ts}'))
+export function loadModuleResolversArray (graphQlPath: string, extensionsPath?: string): any[] {
+  const fileLoaderExt = process.env.VS_ENV && process.env.VS_ENV === 'dev' ? 'ts' : 'js'
```
Comment (Fifciu) [inline packages/lib/helpers/graphql.ts:5]: Let's just simplify it to the:
```ts
const fileLoaderExt = process.env.VS_ENV === 'dev' ? 'ts' : 'js'
```

**Review by Fifciu — CHANGES_REQUESTED** [review]

File: packages/lib/helpers/graphql.ts (hunk 1 above)
Comment (cewald) [reply packages/lib/helpers/graphql.ts]: Done :)

**Review by Fifciu — APPROVED** [review]
Great job thanks
